### ISSUE TITLE
Query final winner of the bid

### ISSUE THREAD

**Issue by yutaro-elk** [UnUniFi/chain#247]
**Is your feature request related to a problem? Please describe.**
I want to know final winner of the bid.

**Comment by yukiwaki** [comment]
@mkXultra 

I still didn't get the win bidder on nft bids, even if the listing state is SUCCESSFUL_BID.
is it because this listing made before your implementation? (i couldn't test it today because of [259 issue](https://github.com/UnUniFi/chain/issues/259). it might work if we make the new NFT bids)

https://ununifi-bubble-test-v6.cauchye.net:1318/ununifi/nftmarket/nft_bids/ununifi-2F877964AAC53FC39A5FCD82F010B50189FBC428/a02

https://ununifi-bubble-test-v6.cauchye.net:1318/ununifi/nftmarket/nft_listing/ununifi-2F877964AAC53FC39A5FCD82F010B50189FBC428/a02

**Comment by mkXultra** [comment]
The highest bidder in nft bids is the winning bidder.
https://ununifi-bubble-test-v6.cauchye.net:1318/ununifi/nftmarket/nft_bids/ununifi-2F877964AAC53FC39A5FCD82F010B50189FBC428/a02

**Comment by yukiwaki** [comment]
@mkXultra 
Noted, so I should just get the highest "paid amount" bidder as winner, right?
