### ISSUE TITLE
impliment unit test for decentralized vault

### ISSUE THREAD

**Issue by mkXultra** [UnUniFi/chain#271]
decentralized vault is less unit testing.
Create the following unit tests

- x/decentralized-vault/genesis_test.go
- x/decentralized-vault/keeper/grpc_query_params_test.go
- x/decentralized-vault/keeper/msg_server_test.go
- x/decentralized-vault/keeper/params_test.go
- x/decentralized-vault/keeper/wrappednft_test.go(implement fix me)

**Comment by hikaruNagamine** [comment]
@mkXultra 
https://github.com/UnUniFi/chain/blob/ac9cb611ff20bb5998301469d2854b4088a58416/x/decentralized-vault/keeper/wrappednft.go#L194
I have a question on test case creation.
I have a question about the conditional expression in this link, but I don't know how to set it to achieve the "return true" condition.
I am wondering if the condition could be something like the following
I thought it might be an error in the conditional expression, since the place where this method is used also displays the error message "this nft is in use".
We apologize for the trouble, but please check.
```go
	if (lisitngNft == nftmarkettypes.NftListing{} || err != nil) {
		return false
	} else {
		return true
	}
```

Sorry if there is a way to "return true". It was my lack of research.
If so, I would appreciate it if you could tell me how to do it, including the conditions!

**Comment by hikaruNagamine** [comment]
a7248a5c847f17cbd8aafd8eb6f64857f1b8ee63
da95f3cae5943974fb824b0a923313d367685f4b

**Comment by mkXultra** [comment]
@hikaruNagamine 
To test for this, we need to LIST the nft.
nftmarketKeeper has a function called Listnft.
Please use it.

**Comment by hikaruNagamine** [comment]
@mkXultra 
Corrected the condition for judging true.
I have added a unit test, so please check there.
e57a471349c4fbb7197952912116213fc0a102ac
